name: recent activity

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          USERNAME: mlgs45
          COMMIT_MSG: "chore: met à jour l'activité récente"
          MAX_LINES: 5
